### ISSUE TITLE
Rename repository to observatorium/deployments

### ISSUE THREAD

**Issue by metalmatze** [observatorium/deployments#282]
With more and more things being added to this repository, it's not only about the initial jsonnet *configuration* anymore. 
Therefore we propose to rename this repository to observatorium/deployments.
Hopefully, it'll be a bit more obvious that this repository contains a few different ways of deploying Observatorium going forward.

/cc @observatorium/maintainers @rollandf @nmagnezi

**Comment by bwplotka** [comment]
Agree (: 

What about something short like `deploy`

**Comment by krasi-georgiev** [comment]
+1 observatorium/deploy

**Comment by squat** [comment]
:+1:

**Comment by kakkoyun** [comment]
If we do this, can we have jsonnet-bundler compatible directory that includes base configuration. That'd be easier to extend in downstream repositories.

**Comment by squat** [comment]
I think that that is something we should do regardless of renaming the repo, no?

**Comment by brancz** [comment]
Don't we have that today? But yes, I agree, it's separate. Let's make other folks aware that we are planning on doing this, if they also give the ok then I'm happy with just moving forward with it.

**Comment by rollandf** [comment]
:+1:

**Comment by nmagnezi** [comment]
👍

**Comment by metalmatze** [comment]
done :)
