### ISSUE TITLE
Documentation - RBAC and tenants

### ISSUE THREAD

**Issue by rollandf** [observatorium/deployments#295]
Add explanations on configuring RBAC and tenants in k8s and OCP

**Comment by squat** [comment]
Note this overlaps with an issue observatorium/observatorium: https://github.com/observatorium/observatorium/issues/64

**Comment by squat** [comment]
I think maybe we should keep the documentation in the observatorium repo to ensure things are not spread out too much. WDYT @rollandf?

**Comment by rollandf** [comment]
Sure. We can refer to the observatorium repo for details.
