### ISSUE TITLE
volumeClaimTemplate does not work

### ISSUE THREAD

**Issue by clyang82** [observatorium/deployments#313]
From here - https://github.com/observatorium/deployments/blob/master/example/manifests/observatorium.yaml we can see that it is allowed to define `volumeClaimTemplate` for store/rule/receiver/compact component. Actually, the operator does not take this definition to apply to each component. the component is still using `emptyDir: {}`. for example: https://github.com/observatorium/deployments/blob/d5ba8dea045be9f219e69357928ee9453a7d6784/environments/base/manifests/thanos-rule-statefulSet.yaml#L77-L80

It seems the thanos does not support https://github.com/thanos-io/kube-thanos/blob/c070408f18b155fca804cd3da7709313b1717965/jsonnet/kube-thanos/kube-thanos-receive.libsonnet#L108-L110

**Comment by brancz** [comment]
emptydir is just the default, the configuration here uses https://github.com/thanos-io/kube-thanos/blob/c070408f18b155fca804cd3da7709313b1717965/jsonnet/kube-thanos/kube-thanos-receive.libsonnet#L191-L212

**Comment by clyang82** [comment]
Thanks @brancz for your response.

Please correct me if I am wrong.

all the manifests (environments/base/manifests and example/manifests/observatorium.yaml) are generated based on https://github.com/observatorium/deployments/blob/master/environments/base/default-config.libsonnet. You can see that for `rule`, `volumeClaimTemplates` is defined https://github.com/observatorium/deployments/blob/d5ba8dea045be9f219e69357928ee9453a7d6784/environments/base/default-config.libsonnet#L75-L90
but the generated manifest does not have `volumeClaimTemplates`
https://github.com/observatorium/deployments/blob/master/environments/base/manifests/thanos-rule-statefulSet.yaml

I think it should be there. otherwise, why we defined it in CR.

**Comment by brancz** [comment]
Yes we need to conditionally merge the volume claim patch, if that's specified in the CR.
