### ISSUE TITLE
Make Loki as an optional

### ISSUE THREAD

**Issue by clyang82** [observatorium/deployments#314]
>Observatorium is a unified service to alert and troubleshoot infrastructure. It combines observability signals such as      metrics, logs, traces, profiles and more in a single experience to reduce mean time to resolution.

In my understanding, the metrics, logs, traces, profiles etc are the components of observatorium. they should not be designed as required components. they are should be optional. we should have one component enabled at least in order to install observatorium operator.

@brancz @squat any comments? Thanks.

**Comment by metalmatze** [comment]
Hm, eventually we will need some sort of requirements on signals to be able to correlate properly. For now, having them optional is fine.
