### ISSUE TITLE
Feature Request: should have a configurable params for enable/disable downsampling

### ISSUE THREAD

**Issue by songleo** [observatorium/deployments#315]
I installed observatorium-operator and found the thanos-compact disable downsampling (`--downsampling.disable`). I didn’t find any config to enable it, we should have this be configurable in the CR. For detail: https://coreos.slack.com/archives/C010A637DGB/p1594884831397400

**Comment by brancz** [comment]
yeah I think making this configurable and have downsampling on by default makes sense

**Comment by clyang82** [comment]
I am working on that.
